; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/pioarduino/platform-espressif32
board = esp32-c5-devkitc-1
framework = espidf
board_build.esp-idf.sdkconfig_path = sdkconfig.esp32-c5-its

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

[env:esp32-c5-its]

[env:esp32-c5-its-full]
build_flags = -D GPS -D SDCARD -D RGB

[env:esp32-c5-its-gps]
build_flags = -D GPS -D RGB

[env:esp32-c5-its-sdcard]
build_flags = -D SDCARD -D RGB

[env:esp32-c5-its-rgb]
build_flags = -D RGB

[env:esp32-c5-its-led]
build_flags = -D LED
